name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_DNS}}
        username: ${{ secrets.USERNAME}}
        key: ${{ secrets.EC2_SSH_KEY }}
        target: ${{ secrets.TARGET_DIR }}

    - name: Restart Nginx on EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST_DNS}}
        username: ${{ secrets.USERNAME}}
        key: ${{ secrets.EC2_SSH_KEY }}
        target: ${{ secrets.TARGET_DIR }}
        script: |
          sudo apt-get -y update
          sudo apt-get install -y apache2
          sudo systemct1 start apache2
          sudo systemct1 enable apache2
          cd home
          sudo mv */var/www/html
