name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0 # Updated to a stable version

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0 # Update to the latest version compatible with Node.js 20
        with:
          node-version: '20' # Explicitly set to the latest supported version

      - name: Deploy to server1
        uses: easingthemes/ssh-deploy@v1.1.0 # Ensure you have the latest version
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.0 # Update to the latest stable version
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd /home
            sudo mv * /var/www/html
